theme: jekyll-theme-cayman

title: PhotoDemon automatic update interface
tagline: the official automatic update server for PhotoDemon 7.2+
locale: "en"
author:
   name: Tanner Helland
   url: https://photodemon.org

pd-stable-v: 7.0.0.1
pd-beta-v: 6.9.0.3395
pd-nightly-v: 7.9.0.2091

